# Generated by Django 6.0.4 on 2026-04-16 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('tagline', models.CharField(help_text='Short tagline shown in the hero section', max_length=200)),
                ('bio', models.TextField(help_text='Detailed biography shown in the About section')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile photo (recommended: 400x400px)', null=True, upload_to='uploads/profile/')),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone / WhatsApp number with country code e.g. +91XXXXXXXXXX', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('resume_file', models.FileField(blank=True, help_text='Downloadable resume (PDF)', null=True, upload_to='uploads/resume/')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('projects_completed', models.PositiveIntegerField(default=0, help_text='Total projects completed')),
                ('clients_served', models.PositiveIntegerField(default=0, help_text='Clients served')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated)', max_length=140, unique=True)),
                ('short_description', models.CharField(help_text='One-line teaser shown on card', max_length=200)),
                ('description', models.TextField(help_text='Full project description')),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or cover image (recommended: 800x500px)', null=True, upload_to='uploads/projects/')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated list of technologies, e.g. Django, React, PostgreSQL', max_length=300)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on portfolio homepage')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon_class', models.CharField(choices=[('devicon-python-plain', 'Python'), ('devicon-javascript-plain', 'JavaScript'), ('devicon-typescript-plain', 'TypeScript'), ('devicon-react-original', 'React'), ('devicon-vuejs-plain', 'Vue.js'), ('devicon-django-plain', 'Django'), ('devicon-nodejs-plain', 'Node.js'), ('devicon-html5-plain', 'HTML5'), ('devicon-css3-plain', 'CSS3'), ('devicon-postgresql-plain', 'PostgreSQL'), ('devicon-mysql-plain', 'MySQL'), ('devicon-mongodb-plain', 'MongoDB'), ('devicon-docker-plain', 'Docker'), ('devicon-git-plain', 'Git'), ('devicon-linux-plain', 'Linux'), ('devicon-amazonwebservices-plain-wordmark', 'AWS'), ('devicon-figma-plain', 'Figma'), ('devicon-tailwindcss-plain', 'Tailwind CSS'), ('devicon-bootstrap-plain', 'Bootstrap'), ('devicon-flutter-plain', 'Flutter'), ('devicon-kotlin-plain', 'Kotlin'), ('devicon-swift-plain', 'Swift'), ('devicon-rust-plain', 'Rust'), ('devicon-go-plain', 'Go'), ('devicon-redis-plain', 'Redis'), ('devicon-graphql-plain', 'GraphQL'), ('devicon-nextjs-plain', 'Next.js'), ('devicon-nuxtjs-plain', 'Nuxt.js'), ('devicon-flask-original', 'Flask'), ('devicon-fastapi-plain', 'FastAPI'), ('custom', 'Custom (use name as icon)')], default='custom', help_text='Devicon CSS class for the skill icon', max_length=80)),
                ('proficiency', models.PositiveSmallIntegerField(default=80, help_text='Proficiency percentage (1–100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on portfolio')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
