# Generated by Django 5.2.13 on 2026-04-21 05:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Certificate name', max_length=150)),
                ('issuer', models.CharField(help_text='Organisation that issued it, e.g. Google, Coursera', max_length=100)),
                ('issue_date', models.DateField(help_text='Date issued')),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiry', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Certificate ID / licence number', max_length=100)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the certificate')),
                ('image', models.ImageField(blank=True, help_text='Badge or certificate image (recommended: 400×300 px)', null=True, upload_to='uploads/certificates/')),
                ('description', models.TextField(blank=True, help_text='Optional: short description of what was covered')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on portfolio')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram handle without @  e.g.  john.doe', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_certificates',
            field=models.BooleanField(default=True, help_text='Show the Certificates section on the portfolio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clients_served',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Include country code, e.g. +91 98765 43210', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Active profile photo shown on the portfolio.', null=True, upload_to='uploads/profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resume/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated: Django, React, PostgreSQL', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(choices=[('devicon-python-plain', 'Python'), ('devicon-javascript-plain', 'JavaScript'), ('devicon-typescript-plain', 'TypeScript'), ('devicon-react-original', 'React'), ('devicon-vuejs-plain', 'Vue.js'), ('devicon-django-plain', 'Django'), ('devicon-nodejs-plain', 'Node.js'), ('devicon-html5-plain', 'HTML5'), ('devicon-css3-plain', 'CSS3'), ('devicon-postgresql-plain', 'PostgreSQL'), ('devicon-mysql-plain', 'MySQL'), ('devicon-mongodb-plain', 'MongoDB'), ('devicon-docker-plain', 'Docker'), ('devicon-git-plain', 'Git'), ('devicon-linux-plain', 'Linux'), ('devicon-amazonwebservices-plain-wordmark', 'AWS'), ('devicon-figma-plain', 'Figma'), ('devicon-tailwindcss-plain', 'Tailwind CSS'), ('devicon-bootstrap-plain', 'Bootstrap'), ('devicon-flutter-plain', 'Flutter'), ('devicon-kotlin-plain', 'Kotlin'), ('devicon-swift-plain', 'Swift'), ('devicon-rust-plain', 'Rust'), ('devicon-go-plain', 'Go'), ('devicon-redis-plain', 'Redis'), ('devicon-graphql-plain', 'GraphQL'), ('devicon-nextjs-plain', 'Next.js'), ('devicon-nuxtjs-plain', 'Nuxt.js'), ('devicon-flask-original', 'Flask'), ('devicon-fastapi-plain', 'FastAPI'), ('custom', 'Custom / Other')], default='custom', max_length=80),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/profile/gallery/')),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'Professional', 'Casual'", max_length=60)),
                ('is_active', models.BooleanField(default=False, help_text='Mark as active to use this as the main profile photo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Profile Photo',
                'verbose_name_plural': 'Profile Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
