# Generated by Django 5.2.13 on 2026-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certificate_profile_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_user_id',
            field=models.CharField(blank=True, help_text='Numeric Instagram User ID e.g. 123456789 (optional)', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bg_color',
            field=models.CharField(blank=True, default='', help_text='CSS colour behind profile photo e.g. #1e293b. Leave blank for gradient.', max_length=30),
        ),
    ]
