# Generated by Django 5.2.13 on 2026-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_fix_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='slot',
            field=models.CharField(choices=[('hero', 'Hero Section  (circular photo on home page)'), ('about', 'About Me Section (rectangular photo beside bio)')], default='hero', help_text='Which section this photo appears in.', max_length=10),
        ),
    ]
